### ISSUE TITLE
专题-赏金猎人系列游戏合集文章图片问题

### ISSUE THREAD

**Issue by ESGame-Ann** [ES-Game/ESGame_Website_BugTracker#1]
图片还显示尺寸
![image](https://user-images.githubusercontent.com/61007846/74424415-7becfd80-4e84-11ea-82ea-cb4de70206e1.png)

**Comment by ESGame-Gloria** [comment]
2020/2/25Gloria:此問題未到問題單層級，只是因為目前無法進行“遊戲"的內容更新或新增（回報狀態：502或503），所以先直接將此遊戲刪除，讓此錯誤不會顯示在前台
