### ISSUE TITLE
EMAIL_ISSUE

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#21]
![email—issue](https://user-images.githubusercontent.com/61268674/84120189-0d056700-aa68-11ea-83c7-5bc7a9f25ec6.jpg)

there shouldn't show off the EMAIL form.

**Comment by ESGame-May** [comment]
This is done , solve by Mr Alex 
you can login by use the email
![Capture](https://user-images.githubusercontent.com/65388497/86333936-c5dd5100-bc76-11ea-9f8c-b736f3dad5c3.PNG)
![1s](https://user-images.githubusercontent.com/65388497/86333949-c970d800-bc76-11ea-94a3-60802ff24def.PNG)

**Comment by ESGame-Gloria** [comment]
old issue ^^
