### ISSUE TITLE
didn't link right page: Giới thiệu(公司簡介）Thỏa thuận người dùng（用戶協議）Chính sách bảo mật

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#23]
![0107-001](https://user-images.githubusercontent.com/61268674/86223943-c7e1da00-bbba-11ea-9cd1-5cc1d8824e54.jpg)

**Comment by ESGame-May** [comment]
Emily is working on it . 
Miss Angela already had the 公司簡介 and 用戶協議 and want to talk to miss glo about this, please talk to her and give the final document to emily so that she can fix this

**Comment by ESGame-Gloria** [comment]
https://www.esgame.vn/index.php?ac=help&op=agreement
please use the old version's contant. thank you ^____^

**Comment by ESGame-Gloria** [comment]
![word different size](https://user-images.githubusercontent.com/61268674/86732575-1849b380-c063-11ea-8408-b9a2d2ff119c.jpg)
please renew the word size. tks:)

**Comment by ESGame-Gloria** [comment]
Some text is bold and some are not, please adjust to be consistent

**Comment by ESGame-Gloria** [comment]
well down, thank you. ^^
