### ISSUE TITLE
HomePage_User

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#24]
didn't show off the user's Mug shot
![0107-003_MEMBER_didnotWithPic](https://user-images.githubusercontent.com/61268674/86224133-13948380-bbbb-11ea-8895-0f3709b2e4cf.jpg)

**Comment by ESGame-May** [comment]
Mr Alex had fix the UI information 
![d](https://user-images.githubusercontent.com/65388497/86334637-b0b4f200-bc77-11ea-8264-ddf65b6d3322.PNG)

**Comment by ESGame-Gloria** [comment]
got it. thank you very much ^^
