### ISSUE TITLE
Game_all game shows the same LOGO

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#25]
all game shows the same LOGO
![0107-002_GAME_miss](https://user-images.githubusercontent.com/61268674/86224250-3757c980-bbbb-11ea-89e9-972d0065700b.jpg)

**Comment by ESGame-May** [comment]
May and Emily will fix this

**Comment by ESGame-Gloria** [comment]
thanks for your attention;)
