### ISSUE TITLE
Member—LOGIN_need change color or pic

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#28]
![0107-006-user-login-need-change-thecolor or pic](https://user-images.githubusercontent.com/61268674/86226474-4ee48180-bbbe-11ea-83b1-269a4955ea60.jpg)
when USER log-in, the "people" icon need to change the color or show off the user's pic

**Comment by ESGame-May** [comment]
Designer is looking for the user random avatar

**Comment by ESGame-Gloria** [comment]
Thank you ^___^

**Comment by ESGame-Gloria** [comment]
well down ^^
