### ISSUE TITLE
手機版型“phone”_wrong icon with word錯誤的ICON

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#30]
![0107-008_phone_wrong icon with word](https://user-images.githubusercontent.com/61268674/86228392-df23c600-bbc0-11ea-9bc7-749f1ffcf08f.jpg)

**Comment by ESGame-May** [comment]
alex working on it ! Soon will be fixed !

**Comment by ESGame-Gloria** [comment]
well down ^__^ Thank you ~
