### ISSUE TITLE
會員MEMBER_shows wrong data已經填了女性，但每次都帶出男性

### ISSUE THREAD

**Issue by ESGame-Gloria** [ES-Game/ESGame_Website_BugTracker#31]
![0107-009_member_wrong_Data](https://user-images.githubusercontent.com/61268674/86230570-d5e82880-bbc3-11ea-92d1-8688410fa423.jpg)
i saved my data already, but every time it shows wrong data~

**Comment by ESGame-May** [comment]
Oleg and Emily is working on it

**Comment by ESGame-Gloria** [comment]
it should shows the data i have already in-put. my input is female(Nu~) but when i open it , it always shows mele(Nam)

**Comment by ESGame-Gloria** [comment]
male
