### ISSUE TITLE
News-新闻-Zoey

### ISSUE THREAD

**Issue by ESGame-Ann** [ES-Game/ESGame_Website_BugTracker#39]
![image](https://user-images.githubusercontent.com/61007846/86232249-daa9de00-bbbd-11ea-9a9b-54acd84e0ff7.png)
- 文章的日期顺序还是按中国的格式
Date form is in Chinese way
- 还没翻译好
Titile hasn't been translated yet.

**Comment by ESGame-Justin** [comment]
fixed
